version: '3'
services:
  aspnetbackend:
    build:
      context: ./aspnetbackend    
    environment:
      - DB_HOST=customerDb
      - DB_NAME=customer
      - DB_SA_PASSWORD=A!VeryComplex123Password
    ports:
      - "5005:5005"
    depends_on:
      - db
  reactfrontend:
    build:
      context: ./reactfrontend
    ports:
      - "3000:3000" 
  db:
    container_name: customerDb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: A!VeryComplex123Password     
    ports:
      - 1433:1433
    volumes:
      - db-data:/var/opt/mssql 
    restart: always 

volumes:
  db-data:
   
        