version: '3'
services:
  aspnetbackend:
    build:
      context: ./aspnetbackend
    ports:
      - "5005:5005"
  reactfrontend:
    build:
      context: ./reactfrontend
    ports:
      - "3000:3000"
    depends_on:
      - db  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: S3cur3P@ssW0rd!
      ACCEPT_EULA: Y    
        