---
name: Build-Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and tag images
      run: |
        docker-compose build
        docker tag aspnet-6-react-docker_aspnetbackend gudmon/aspnet6reactjs-backend
        docker tag aspnet-6-react-docker_reactfrontend gudmon/aspnet6reactjs-frontend

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push images to Docker Hub
      run: | 
        docker push gudmon/aspnet6reactjs-backend
        docker push gudmon/aspnet6reactjs-frontend
